[project]
name = "rzadb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "soue27", email = "man.dozor@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.6",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "sqlalchemy[asyncio]>=2.0.52",
    "uuid6>=2025.0.1",
    "uvicorn[standard]>=0.53.0",
]


[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.6",
]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "strict"
