"""make schema editable file optional

Revision ID: 0f6e039b6b54
Revises: bad0f520ecdf
Create Date: 2026-09-13 14:26:49.105718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6e039b6b54'
down_revision: Union[str, Sequence[str], None] = 'bad0f520ecdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schema_records', 'editable_file_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schema_records', 'editable_file_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
