"""add maintenance record

Revision ID: 105552fb6d6b
Revises: 60bd30189d01
Create Date: 2026-09-13 09:14:19.019653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '105552fb6d6b'
down_revision: Union[str, Sequence[str], None] = '60bd30189d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_records',
    sa.Column('urza_id', sa.Uuid(), nullable=False),
    sa.Column('historical_data', sa.Text(), nullable=True),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
                    sa.Column(
                        'maintenance_type',
                        postgresql.ENUM(
                            'В',
                            'К',
                            'К1',
                            'Н',
                            'Т',
                            'ТК',
                            'О',
                            'ОСМ',
                            'ВП',
                            'ПП',
                            name='maintenance_type',
                            create_type=False,
                        ),
                        nullable=False,
                    ),
    sa.Column('detected_deviations', sa.Text(), nullable=False),
    sa.Column('measures_taken', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('scan_protocol_id', sa.Uuid(), nullable=True),
    sa.Column('editable_protocol_id', sa.Uuid(), nullable=True),
    sa.Column('signed_form_file_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['editable_protocol_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_protocol_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['signed_form_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['urza_id'], ['urzas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_records')
    # ### end Alembic commands ###
