"""create connections

Revision ID: 1c77b5e4eec3
Revises: 8833008b69cb
Create Date: 2026-09-12 17:57:45.322298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c77b5e4eec3'
down_revision: Union[str, Sequence[str], None] = '8833008b69cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('substation_id', sa.Uuid(), nullable=False),
    sa.Column('dispatch_name', sa.String(length=255), nullable=False),
    sa.Column('sap_code', sa.String(length=64), nullable=True),
    sa.Column('asureo_code', sa.String(length=64), nullable=True),
    sa.Column('rdu_subordination', sa.Boolean(), nullable=False),
    sa.Column('operational_current_type', sa.Enum('permanent', 'rectified', 'alternating', name='operational_current_type'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    # ### end Alembic commands ###
