"""add rza instruction

Revision ID: 1d2e35f981c7
Revises: 3c9641f2a004
Create Date: 2026-09-13 08:56:29.887664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2e35f981c7'
down_revision: Union[str, Sequence[str], None] = '3c9641f2a004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rza_instructions',
    sa.Column('substation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('substation_id')
    )
    op.create_table('rza_instruction_versions',
    sa.Column('rza_instruction_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('change_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('scan_file_id', sa.Uuid(), nullable=False),
    sa.Column('editable_file_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['editable_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['rza_instruction_id'], ['rza_instructions.id'], ),
    sa.ForeignKeyConstraint(['scan_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rza_instruction_versions')
    op.drop_table('rza_instructions')
    # ### end Alembic commands ###
