"""add schema records

Revision ID: 3c9641f2a004
Revises: 1128c0e35b69
Create Date: 2026-09-13 08:49:56.364674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9641f2a004'
down_revision: Union[str, Sequence[str], None] = '1128c0e35b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_forms',
    sa.Column('urza_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['urza_id'], ['urzas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urza_id')
    )
    op.create_table('schema_records',
    sa.Column('schema_form_id', sa.Uuid(), nullable=False),
    sa.Column('schema_number', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=500), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=False),
    sa.Column('change_justification', sa.Text(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('scan_file_id', sa.Uuid(), nullable=False),
    sa.Column('editable_file_id', sa.Uuid(), nullable=False),
    sa.Column('signed_form_file_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['editable_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['schema_form_id'], ['schema_forms.id'], ),
    sa.ForeignKeyConstraint(['signed_form_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_records')
    op.drop_table('schema_forms')
    # ### end Alembic commands ###
