"""create otd versions

Revision ID: 488b69c3e6c7
Revises: 124518313415
Create Date: 2026-09-12 21:22:14.043397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488b69c3e6c7'
down_revision: Union[str, Sequence[str], None] = '124518313415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otd_versions',
    sa.Column('otd_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('panel_cabinet_type', sa.String(length=255), nullable=True),
    sa.Column('panel_cabinet_serial', sa.String(length=128), nullable=True),
    sa.Column('panel_cabinet_manufacture_year', sa.SmallInteger(), nullable=True),
    sa.Column('terminal_type', sa.String(length=255), nullable=True),
    sa.Column('terminal_serial', sa.String(length=128), nullable=True),
    sa.Column('terminal_manufacture_year', sa.SmallInteger(), nullable=True),
    sa.Column('urza_service_life', sa.Integer(), nullable=False),
    sa.Column('software_version', sa.String(length=128), nullable=True),
    sa.Column('ct_ratio', sa.String(length=64), nullable=True),
    sa.Column('vt_ratio', sa.String(length=64), nullable=True),
    sa.Column('urza_scheme_designation', sa.String(length=255), nullable=True),
    sa.Column('urza_purpose', sa.Enum('rza', 'sa', 'pa', 'ra', name='otd_purpose'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['otd_id'], ['otds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otd_versions')
    # ### end Alembic commands ###
