"""make schema scan file optional

Revision ID: 5060b64db383
Revises: 0f6e039b6b54
Create Date: 2026-09-13 14:34:09.846465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5060b64db383'
down_revision: Union[str, Sequence[str], None] = '0f6e039b6b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schema_records', 'scan_file_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schema_records', 'scan_file_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
