"""add selectivity schemes

Revision ID: 5fd04138bcdb
Revises: d09ea1426033
Create Date: 2026-09-22 21:08:37.733280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd04138bcdb'
down_revision: Union[str, Sequence[str], None] = 'd09ea1426033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selectivity_schemes',
    sa.Column('substation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('substation_id')
    )
    op.create_table('selectivity_scheme_versions',
    sa.Column('selectivity_scheme_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('change_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('scan_file_id', sa.Uuid(), nullable=False),
    sa.Column('editable_file_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['editable_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['selectivity_scheme_id'], ['selectivity_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selectivity_scheme_versions')
    op.drop_table('selectivity_schemes')
    # ### end Alembic commands ###
