"""add urza instruction

Revision ID: 60bd30189d01
Revises: 1d2e35f981c7
Create Date: 2026-09-13 09:02:13.154443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bd30189d01'
down_revision: Union[str, Sequence[str], None] = '1d2e35f981c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urza_instructions',
    sa.Column('urza_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['urza_id'], ['urzas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urza_id')
    )
    op.create_table('urza_instruction_versions',
    sa.Column('urza_instruction_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('change_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('scan_file_id', sa.Uuid(), nullable=False),
    sa.Column('editable_file_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['editable_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['urza_instruction_id'], ['urza_instructions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urza_instruction_versions')
    op.drop_table('urza_instructions')
    # ### end Alembic commands ###
