"""add settings record

Revision ID: 61a41df6d720
Revises: 9600d57ceeaa
Create Date: 2026-09-13 08:06:12.886745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a41df6d720'
down_revision: Union[str, Sequence[str], None] = '9600d57ceeaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_records',
    sa.Column('settings_form_id', sa.Uuid(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('initial_setting', sa.Text(), nullable=False),
    sa.Column('new_setting', sa.Text(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('signed_form_file_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['settings_form_id'], ['settings_forms.id'], ),
    sa.ForeignKeyConstraint(['signed_form_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_records')
    # ### end Alembic commands ###
