"""add otd version uniqueness

Revision ID: 7a83176e4623
Revises: 488b69c3e6c7
Create Date: 2026-09-12 21:24:29.633734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a83176e4623'
down_revision: Union[str, Sequence[str], None] = '488b69c3e6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_otd_versions_otd_id_version_number', 'otd_versions', ['otd_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_otd_versions_otd_id_version_number', 'otd_versions', type_='unique')
    # ### end Alembic commands ###
