"""add maintenance period rules

Revision ID: 7b74959b13cb
Revises: e94fff066416
Create Date: 2026-09-13 09:24:27.417340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7b74959b13cb'
down_revision: Union[str, Sequence[str], None] = 'e94fff066416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_period_rules',
                    sa.Column(
                        'room_category',
                        postgresql.ENUM(
                            'I',
                            'II',
                            'III',
                            name='room_category',
                            create_type=False,
                        ),
                        nullable=False,
                    ),
                    sa.Column(
                        'element_base',
                        postgresql.ENUM(
                            'electromechanical',
                            'microelectronic',
                            'microprocessor',
                            name='element_base',
                            create_type=False,
                        ),
                        nullable=False,
                    ),
    sa.Column('maintenance_period_years', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_category', 'element_base', name='uq_maintenance_period_rule_category_element')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_period_rules')
    # ### end Alembic commands ###
