"""create substations

Revision ID: 8833008b69cb
Revises: 3b0ab304d77e
Create Date: 2026-09-12 17:31:32.862437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8833008b69cb'
down_revision: Union[str, Sequence[str], None] = '3b0ab304d77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('substations',
    sa.Column('enterprise_id', sa.Uuid(), nullable=False),
    sa.Column('highest_voltage', sa.Enum('500', '220', '110', '35', '10', '6', '0.4', name='highest_voltage'), nullable=False),
    sa.Column('dispatch_name', sa.String(length=255), nullable=False),
    sa.Column('sap_code', sa.String(length=64), nullable=True),
    sa.Column('asureo_code', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substations')
    # ### end Alembic commands ###
