"""add task link to otd version

Revision ID: bad0f520ecdf
Revises: 7b74959b13cb
Create Date: 2026-09-13 12:32:51.233137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad0f520ecdf'
down_revision: Union[str, Sequence[str], None] = '7b74959b13cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otd_versions', sa.Column('task_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'otd_versions', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otd_versions', type_='foreignkey')
    op.drop_column('otd_versions', 'task_id')
    # ### end Alembic commands ###
