"""add inspection models

Revision ID: d09ea1426033
Revises: 5060b64db383
Create Date: 2026-09-13 19:50:29.123258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "d09ea1426033"
down_revision: Union[str, Sequence[str], None] = "5060b64db383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspection_tasks",
        sa.Column("substation_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "created",
                "assigned",
                "in_progress",
                "completed",
                "under_review",
                "closed",
                "rejected",
                name="task_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "acceptance_deadline_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["substation_id"], ["substations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "inspection_history",
        sa.Column("inspection_task_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "old_status",
            postgresql.ENUM(
                "created",
                "assigned",
                "in_progress",
                "completed",
                "under_review",
                "closed",
                "rejected",
                name="task_status",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            postgresql.ENUM(
                "created",
                "assigned",
                "in_progress",
                "completed",
                "under_review",
                "closed",
                "rejected",
                name="task_status",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"]),
        sa.ForeignKeyConstraint(
            ["inspection_task_id"],
            ["inspection_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "inspections",
        sa.Column("substation_id", sa.Uuid(), nullable=False),
        sa.Column("inspection_task_id", sa.Uuid(), nullable=False),
        sa.Column("inspection_date", sa.Date(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=False),
        sa.Column("scan_file_id", sa.Uuid(), nullable=True),
        sa.Column("editable_file_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["editable_file_id"], ["files.id"]),
        sa.ForeignKeyConstraint(
            ["inspection_task_id"],
            ["inspection_tasks.id"],
        ),
        sa.ForeignKeyConstraint(["scan_file_id"], ["files.id"]),
        sa.ForeignKeyConstraint(["substation_id"], ["substations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("inspection_task_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inspections")
    op.drop_table("inspection_history")
    op.drop_table("inspection_tasks")
    # ### end Alembic commands ###