"""add program

Revision ID: e94fff066416
Revises: 105552fb6d6b
Create Date: 2026-09-13 09:20:15.182556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94fff066416'
down_revision: Union[str, Sequence[str], None] = '105552fb6d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('urza_id', sa.Uuid(), nullable=False),
    sa.Column('program_type', sa.Enum('commissioning', 'decommissioning', 'work', name='program_type'), nullable=False),
    sa.Column('program_number', sa.String(length=255), nullable=False),
    sa.Column('scan_file_id', sa.Uuid(), nullable=False),
    sa.Column('editable_file_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['editable_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['urza_id'], ['urzas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs')
    # ### end Alembic commands ###
