"""create urzas

Revision ID: ff28eb391d54
Revises: 1c77b5e4eec3
Create Date: 2026-09-12 18:07:42.058701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff28eb391d54'
down_revision: Union[str, Sequence[str], None] = '1c77b5e4eec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urzas',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('dispatch_name', sa.String(length=255), nullable=False),
    sa.Column('rdu_subordination', sa.Boolean(), nullable=False),
    sa.Column('inventory_number', sa.String(length=64), nullable=True),
    sa.Column('commissioning_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('in_operation', 'in_repair', 'decommissioned', 'reserve', name='urza_status'), nullable=False),
    sa.Column('element_base', sa.Enum('electromechanical', 'microelectronic', 'microprocessor', name='element_base'), nullable=False),
    sa.Column('category', sa.Enum('I', 'II', 'III', 'IV', name='urza_category'), nullable=False),
    sa.Column('room_category', sa.Enum('I', 'II', 'III', name='room_category'), nullable=False),
    sa.Column('complexity', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urzas')
    # ### end Alembic commands ###
